id: P9BDF8ABA
initial_creation_type: input
source_metadata:
  title: Mayum Tsering Wangmo Series
  language: de
  description: 'Texts by and about Pema Tsering Wangmo (padma tshe ring dbang mo)
    of the Lakar family, the mother of the Seventh Dzogchen Rinpoche and Sogyal Rinpoche:'
  volume:
    51a5d9af2b394b7192a61ade55316253:
      title: A Brief History of the Lakar Family
      parent: History
    d98e867dfe934933b48757f0f36f32f9:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
created_at: '2022-03-01T00:44:27.787086'
last_modified_at: '2022-03-01T00:44:27.787088'
